export const dummyProjects = [
    {
        id: 1,
        ProjectTheme: 'Project Alpha',
        Reason: 'New init',
        Type: 'Research',
        Division: 'Div A',
        Category: 'Tech',
        Priority: 'High',
        Department: 'R&D',
        StartDate: '2023-01-15',
        EndDate: '2023-06-30',
        Location: 'Mumbai',
        Status: 'Running',
    },
    {
        id: 2,
        ProjectTheme: 'Project Beta',
        Reason: 'Cost',
        Type: 'Cost Mgmt',
        Division: 'Div B',
        Category: 'Finance',
        Priority: 'Med',
        Department: 'Finance',
        StartDate: '2023-02-10',
        EndDate: '2023-08-10',
        Location: 'Delhi',
        Status: 'Closed',
    },
    {
        id: 3,
        ProjectTheme: 'Project Gamma',
        Reason: 'Increase prod',
        Type: 'Production',
        Division: 'Div C',
        Category: 'Manufac',
        Priority: 'High',
        Department: 'Prod',
        StartDate: '2023-03-05',
        EndDate: '2023-09-15',
        Location: 'Chennai',
        Status: 'Cancelled',
    },
    {
        id: 4,
        ProjectTheme: 'Project Delta',
        Reason: 'Research',
        Type: 'Study',
        Division: 'Div A',
        Category: 'Tech',
        Priority: 'Low',
        Department: 'R&D',
        StartDate: '2023-01-10',
        EndDate: '2023-04-20',
        Location: 'Pune',
        Status: 'Running',
    },
    {
        id: 5,
        ProjectTheme: 'Project Epsilon',
        Reason: 'Analysis',
        Type: 'Review',
        Division: 'Div B',
        Category: 'Finance',
        Priority: 'High',
        Department: 'Finance',
        StartDate: '2023-02-15',
        EndDate: '2023-06-01',
        Location: 'Kolkata',
        Status: 'Open',
    },
    {
        id: 6,
        ProjectTheme: 'Project Zeta',
        Reason: 'Upgrade',
        Type: 'Deployment',
        Division: 'Div C',
        Category: 'IT',
        Priority: 'Med',
        Department: 'IT',
        StartDate: '2023-03-01',
        EndDate: '2023-05-15',
        Location: 'Hyderabad',
        Status: 'Running',
    },
    {
        id: 7,
        ProjectTheme: 'Project Eta',
        Reason: 'Training',
        Type: 'Workshop',
        Division: 'Div A',
        Category: 'HR',
        Priority: 'High',
        Department: 'HR',
        StartDate: '2023-04-10',
        EndDate: '2023-08-10',
        Location: 'Bangalore',
        Status: 'Closed',
    },
    {
        id: 8,
        ProjectTheme: 'Project Theta',
        Reason: 'Expansion',
        Type: 'Growth',
        Division: 'Div B',
        Category: 'Sales',
        Priority: 'Low',
        Department: 'Sales',
        StartDate: '2023-05-20',
        EndDate: '2023-10-15',
        Location: 'Ahmedabad',
        Status: 'Running',
    },
    {
        id: 9,
        ProjectTheme: 'Project Iota',
        Reason: 'Research',
        Type: 'Test',
        Division: 'Div C',
        Category: 'Tech',
        Priority: 'Med',
        Department: 'R&D',
        StartDate: '2023-06-01',
        EndDate: '2023-09-01',
        Location: 'Mumbai',
        Status: 'Open',
    },
    {
        id: 10,
        ProjectTheme: 'Project Kappa',
        Reason: 'Cost',
        Type: 'Audit',
        Division: 'Div A',
        Category: 'Finance',
        Priority: 'High',
        Department: 'Finance',
        StartDate: '2023-07-10',
        EndDate: '2023-12-10',
        Location: 'Delhi',
        Status: 'Cancelled',
    },
    {
        id: 11,
        ProjectTheme: 'Project Lambda',
        Reason: 'Development',
        Type: 'Build',
        Division: 'Div B',
        Category: 'Tech',
        Priority: 'Med',
        Department: 'IT',
        StartDate: '2023-08-01',
        EndDate: '2023-11-30',
        Location: 'Chennai',
        Status: 'Running',
    },
    {
        id: 12,
        ProjectTheme: 'Project Mu',
        Reason: 'Compliance',
        Type: 'Review',
        Division: 'Div C',
        Category: 'HR',
        Priority: 'High',
        Department: 'HR',
        StartDate: '2023-09-15',
        EndDate: '2023-12-15',
        Location: 'Bangalore',
        Status: 'Closed',
    },
    {
        id: 13,
        ProjectTheme: 'Project Nu',
        Reason: 'Feedback',
        Type: 'Survey',
        Division: 'Div A',
        Category: 'Sales',
        Priority: 'Low',
        Department: 'Sales',
        StartDate: '2023-10-01',
        EndDate: '2023-12-30',
        Location: 'Pune',
        Status: 'Running',
    },
    {
        id: 14,
        ProjectTheme: 'Project Xi',
        Reason: 'Launch',
        Type: 'Event',
        Division: 'Div B',
        Category: 'Marketing',
        Priority: 'Med',
        Department: 'Marketing',
        StartDate: '2023-11-01',
        EndDate: '2023-11-20',
        Location: 'Mumbai',
        Status: 'Closed',
    },
    {
        id: 15,
        ProjectTheme: 'Project Omicron',
        Reason: 'Upgrade',
        Type: 'Refresh',
        Division: 'Div C',
        Category: 'Tech',
        Priority: 'High',
        Department: 'IT',
        StartDate: '2023-12-01',
        EndDate: '2024-01-15',
        Location: 'Hyderabad',
        Status: 'Open',
    },
    {
        id: 16,
        ProjectTheme: 'Project Pi',
        Reason: 'Reduction',
        Type: 'Streamline',
        Division: 'Div A',
        Category: 'Finance',
        Priority: 'High',
        Department: 'Finance',
        StartDate: '2024-01-05',
        EndDate: '2024-02-10',
        Location: 'Delhi',
        Status: 'Running',
    },
    {
        id: 17,
        ProjectTheme: 'Project Rho',
        Reason: 'Integration',
        Type: 'Link',
        Division: 'Div B',
        Category: 'Operations',
        Priority: 'Med',
        Department: 'Ops',
        StartDate: '2024-02-01',
        EndDate: '2024-05-01',
        Location: 'Kolkata',
        Status: 'Open',
    },
    {
        id: 18,
        ProjectTheme: 'Project Sigma',
        Reason: 'Innovation',
        Type: 'New idea',
        Division: 'Div C',
        Category: 'Tech',
        Priority: 'Low',
        Department: 'R&D',
        StartDate: '2024-03-01',
        EndDate: '2024-06-01',
        Location: 'Chennai',
        Status: 'Cancelled',
    },
    {
        id: 19,
        ProjectTheme: 'Project Tau',
        Reason: 'Testing',
        Type: 'QA',
        Division: 'Div A',
        Category: 'Tech',
        Priority: 'High',
        Department: 'IT',
        StartDate: '2024-04-01',
        EndDate: '2024-07-15',
        Location: 'Mumbai',
        Status: 'Running',
    },
    {
        id: 20,
        ProjectTheme: 'Project Upsilon',
        Reason: 'Analysis',
        Type: 'Review',
        Division: 'Div B',
        Category: 'Finance',
        Priority: 'Medium',
        Department: 'Finance',
        StartDate: '2024-05-01',
        EndDate: '2024-08-15',
        Location: 'Delhi',
        Status: 'Open',
    },
    {
        id: 21,
        ProjectTheme: 'Project Phi',
        Reason: 'Evaluation',
        Type: 'Check',
        Division: 'Div C',
        Category: 'HR',
        Priority: 'Low',
        Department: 'HR',
        StartDate: '2024-06-01',
        EndDate: '2024-09-01',
        Location: 'Bangalore',
        Status: 'Closed',
    },
    {
        id: 22,
        ProjectTheme: 'Project Chi',
        Reason: 'Strategy',
        Type: 'Plan',
        Division: 'Div A',
        Category: 'Marketing',
        Priority: 'High',
        Department: 'Mktg',
        StartDate: '2024-07-01',
        EndDate: '2024-10-01',
        Location: 'Mumbai',
        Status: 'Open',
    },
    {
        id: 23,
        ProjectTheme: 'Project Psi',
        Reason: 'Review',
        Type: 'Update',
        Division: 'Div B',
        Category: 'Finance',
        Priority: 'Medium',
        Department: 'Finance',
        StartDate: '2024-08-15',
        EndDate: '2024-11-15',
        Location: 'Delhi',
        Status: 'Running',
    },
    {
        id: 24,
        ProjectTheme: 'Project Omega',
        Reason: 'Launch',
        Type: 'New',
        Division: 'Div C',
        Category: 'Tech',
        Priority: 'Low',
        Department: 'R&D',
        StartDate: '2024-09-01',
        EndDate: '2024-12-01',
        Location: 'Bangalore',
        Status: 'Closed',
    },
    {
        id: 25,
        ProjectTheme: 'Project Zeta2',
        Reason: 'Improvement',
        Type: 'Enhance',
        Division: 'Div A',
        Category: 'Operations',
        Priority: 'High',
        Department: 'Ops',
        StartDate: '2024-10-10',
        EndDate: '2024-12-30',
        Location: 'Chennai',
        Status: 'Running',
    },
    {
        id: 26,
        ProjectTheme: 'Project Eta2',
        Reason: 'Pilot',
        Type: 'Test',
        Division: 'Div B',
        Category: 'Sales',
        Priority: 'Medium',
        Department: 'Sales',
        StartDate: '2024-11-01',
        EndDate: '2024-12-15',
        Location: 'Pune',
        Status: 'Open',
    },
    {
        id: 27,
        ProjectTheme: 'Project Theta2',
        Reason: 'Collaboration',
        Type: 'Joint',
        Division: 'Div C',
        Category: 'HR',
        Priority: 'Low',
        Department: 'HR',
        StartDate: '2024-11-20',
        EndDate: '2025-01-15',
        Location: 'Delhi',
        Status: 'Cancelled',
    },
    {
        id: 28,
        ProjectTheme: 'Project Iota2',
        Reason: 'Analysis',
        Type: 'Study',
        Division: 'Div A',
        Category: 'Finance',
        Priority: 'High',
        Department: 'Finance',
        StartDate: '2025-01-01',
        EndDate: '2025-03-01',
        Location: 'Mumbai',
        Status: 'Open',
    },
    {
        id: 29,
        ProjectTheme: 'Project Kappa2',
        Reason: 'Survey',
        Type: 'Data',
        Division: 'Div B',
        Category: 'Marketing',
        Priority: 'Medium',
        Department: 'Mktg',
        StartDate: '2025-02-01',
        EndDate: '2025-04-01',
        Location: 'Kolkata',
        Status: 'Running',
    },
    {
        id: 30,
        ProjectTheme: 'Project Lambda2',
        Reason: 'Assessment',
        Type: 'Check',
        Division: 'Div C',
        Category: 'IT',
        Priority: 'Low',
        Department: 'IT',
        StartDate: '2025-03-01',
        EndDate: '2025-05-15',
        Location: 'Hyderabad',
        Status: 'Closed',
    },
    {
        id: 31,
        ProjectTheme: 'Project Mu2',
        Reason: 'Feedback',
        Type: 'Gather',
        Division: 'Div A',
        Category: 'Sales',
        Priority: 'High',
        Department: 'Sales',
        StartDate: '2025-04-01',
        EndDate: '2025-06-01',
        Location: 'Chennai',
        Status: 'Running',
    },
];

